language: go
go:
- 1.14.x
env:
- BIN_NAME=mvn_resolver
jobs:
  include:
  - stage: Test
    script: go test -v -race ./...
  - stage: Build
    script: go build
  - stage: Deploy
    if: tag IS present
    script:
    - export GOOS=linux && export GOARCH=386 && go build -o ${BIN_NAME}
    - tar -czvf ${BIN_NAME}-${TRAVIS_TAG}-${GOOS}-${GOARCH}.tgz ${BIN_NAME} LICENSE
    - export GOOS=windows && export GOARCH=386 && go build -o ${BIN_NAME}.exe
    - tar -czvf ${BIN_NAME}-${TRAVIS_TAG}-${GOOS}-${GOARCH}.tgz ${BIN_NAME}.exe LICENSE
    - export GOOS=linux && GOARCH=amd64 && go build -o ${BIN_NAME}
    - tar -czvf ${BIN_NAME}-${TRAVIS_TAG}-${GOOS}-${GOARCH}.tgz ${BIN_NAME} LICENSE
    - export GOOS=darwin && export GOARCH=amd64 && go build -o ${BIN_NAME}
    - tar -czvf ${BIN_NAME}-${TRAVIS_TAG}-${GOOS}-${GOARCH}.tgz ${BIN_NAME} LICENSE
    - export GOOS=windows && export GOARCH=amd64 && go build -o ${BIN_NAME}.exe
    - tar -czvf ${BIN_NAME}-${TRAVIS_TAG}-${GOOS}-${GOARCH}.tgz ${BIN_NAME}.exe LICENSE
    deploy:
      provider: releases
      api_key:
        secure: cgJhlN4+EyTYLtc4pnGPPqzQ/S1A+/S7aqwVmXnUK+gfL0Ti/c432ycKl0pFiKs64elejHOqmiu6xmxzyv7SM9yErOgeqGa7tjw7XzuSmyJfv5fzjM/PEQcKbi83ZKgLGyC8PxJ/cCwmNmOpXOXUZXmz7aPN5apdpEjLJ1GySs+d1xWv4haqFScMYXgBo0OdFzjDQdTmjOYi5HjFPnyGOzCpFbpTu1rQ0nmJ7AGxX3+/pRKxPTDARKazUC/NuR2SLVsBuyk/xCmeIjzk0qQemJnowkjyfTlI7WqN8j76YMD5SSwX7dEptn+2PxcoUKrBxSDfPxGqkfk7ePk08v/U8bfw71LxwTFKJ/T/8NkmOs/UrC2xOwPXDsSplkojJk4UhKNK2OhlREv6F9fumnHsR6DYQgoh9BQ1fOvakYKZPmWhY4uhQuAfWc0cwkIo/w8UEmakDlOfYTbdXcbb2HtAgTAoFkJAkP/8Z4KCT2ZsAIwflBEqs2phd2EnflEEeYz3Aj0AbguxP0RGUI8f0jE+kFt5K3IPSivsB7zOc/CriEbYdRcUTvQcKojdNEMiEL+YBjcEzWP9uRjuqGrjzXRVM72Im66XsOtdX5BlnqYh6sM6URir7FBfuZQviuWr3EK+6kk/2DA2y48GgwKIQCWympbS9ZQKHk4G2s5agawogFo=
      file_glob: true
      file: "./*.tgz"
      skip_cleanup: true
      on:
        tags: true
