language: go
go:
- 1.14.x
env:
- BIN_NAME=mvn_resolver
jobs:
  include:
  - stage: Test
    script: go test -v -race ./...
  - stage: Build
    script: go build
  - stage: Deploy
    if: tag IS present
    script:
    - export GOOS=linux && export GOARCH=386 && go build -o ${BIN_NAME}
    - tar -czvf ${BIN_NAME}-${TRAVIS_TAG}-${GOOS}-${GOARCH}.tgz ${BIN_NAME} LICENSE
    - export GOOS=windows && export GOARCH=386 && go build -o ${BIN_NAME}.exe
    - tar -czvf ${BIN_NAME}-${TRAVIS_TAG}-${GOOS}-${GOARCH}.tgz ${BIN_NAME}.exe LICENSE
    - export GOOS=linux && GOARCH=amd64 && go build -o ${BIN_NAME}
    - tar -czvf ${BIN_NAME}-${TRAVIS_TAG}-${GOOS}-${GOARCH}.tgz ${BIN_NAME} LICENSE
    - export GOOS=darwin && export GOARCH=amd64 && go build -o ${BIN_NAME}
    - tar -czvf ${BIN_NAME}-${TRAVIS_TAG}-${GOOS}-${GOARCH}.tgz ${BIN_NAME} LICENSE
    - export GOOS=windows && export GOARCH=amd64 && go build -o ${BIN_NAME}.exe
    - tar -czvf ${BIN_NAME}-${TRAVIS_TAG}-${GOOS}-${GOARCH}.tgz ${BIN_NAME}.exe LICENSE
    deploy:
      provider: releases
      api_key:
        secure: NjuXJjaLaIMxhwy5G1VFToQEPMG15AkFWA5VdTobC2BetLcoJWbL+xFTQTBpYWkXvniBTfkXKhMiBcWnVPhhQIHZLDEGvfS1ZFNKSMvEahxzp9iEQcGyigZMTirRg0v9RW6loROr28mwVqCzQa/NcZAD8CLtCpI5B0XXY2VZTqqkQ66GP81jluaKB12WqO024QoiN1x38qVMIYKTO1ajjfw3vQmJ4ZYURzQUyU3VVhZtEPTwq8f11WqmrZ2r3W6tyzgezjfao6T7BEf0/95SCS6wG+lf4msuvxZ3OBJ9qTdQ3thO7kR7I8zTxwWSyyk8Rhk8jGp3LK3c3brHFZcG/5ry7XwufP3cMvSdAjqh3C3HNY75rvaEPimAB8eg7PAAI+ehg4so4JS7g6jcIc7dCxk/6+uf+SAmgD6g+FRjuSpiglSAlJhIRu34oZ/BniKZUwELScNERW7dshH6hjXNAcheVDuX48NxvBFdrEmgJpVAzTaWDVTL8sdhUgdhHPPAmFnqz9mgDN8ogxWQTL6iAnqyVoJAZzl5iLaycwbX2nDq7HDfDnApQWDMQjb21Ox/Ijq/RKJh5DuYdYMobsyENcB78vCNdQemzdfVggNTfP0NLQ/Z4MjZpCYfqwWZih743hZXH4Ecasso7Rsgs6gPL2iKm2yYCg2dRvSIgADVda0=
      file_glob: true
      file: "./*.tgz"
      skip_cleanup: true
      on:
        tags: true
